// services/mockData.js — All mock data for Pull-Sync

export const MOCK_USERS = [
  { id: "u1", name: "Alex Rivera", email: "alex@pullsync.dev", avatar: "AR", role: "owner" },
  { id: "u2", name: "Sam Chen", email: "sam@pullsync.dev", avatar: "SC", role: "reviewer" },
  { id: "u3", name: "Jordan Kim", email: "jordan@pullsync.dev", avatar: "JK", role: "reviewer" },
  { id: "u4", name: "Taylor West", email: "taylor@pullsync.dev", avatar: "TW", role: "viewer" },
];

export const MOCK_PRS = [
  {
    id: "pr-1",
    number: 247,
    title: "feat: implement real-time collaborative editing with CRDT",
    description: "This PR introduces conflict-free replicated data types for collaborative text editing. It replaces the existing lock-based system with a fully distributed approach that allows simultaneous edits without conflicts.\n\n## Changes\n- Added `@syncedstore/core` dependency\n- Implemented CRDT document model\n- Updated WebSocket handlers\n- Added operational transform fallback",
    authorId: "u1",
    author: "Alex Rivera",
    reviewers: ["u2", "u3"],
    status: "open",
    branch: "feat/crdt-collab",
    baseBranch: "main",
    commitsCount: 12,
    changedFiles: 8,
    additions: 342,
    deletions: 89,
    createdAt: "2024-03-15T10:30:00Z",
    updatedAt: "2024-03-15T14:22:00Z",
    commentCount: 7,
    labels: ["feature", "breaking-change"],
  },
  {
    id: "pr-2",
    number: 246,
    title: "fix: resolve race condition in webhook delivery queue",
    description: "Fixes a critical race condition where webhook events could be delivered out of order under high load. Added mutex locks and a proper delivery queue with retry logic.",
    authorId: "u2",
    author: "Sam Chen",
    reviewers: ["u1"],
    status: "approved",
    branch: "fix/webhook-race",
    baseBranch: "main",
    commitsCount: 3,
    changedFiles: 4,
    additions: 67,
    deletions: 23,
    createdAt: "2024-03-14T09:15:00Z",
    updatedAt: "2024-03-14T16:45:00Z",
    commentCount: 3,
    labels: ["bug", "critical"],
  },
  {
    id: "pr-3",
    number: 245,
    title: "refactor: migrate auth service to OAuth 2.0 PKCE flow",
    description: "Migrates authentication from implicit flow to PKCE (Proof Key for Code Exchange) for enhanced security.",
    authorId: "u3",
    author: "Jordan Kim",
    reviewers: ["u1", "u2"],
    status: "rejected",
    branch: "refactor/oauth-pkce",
    baseBranch: "main",
    commitsCount: 6,
    changedFiles: 11,
    additions: 189,
    deletions: 234,
    createdAt: "2024-03-13T11:00:00Z",
    updatedAt: "2024-03-13T18:30:00Z",
    commentCount: 12,
    labels: ["security", "refactor"],
  },
  {
    id: "pr-4",
    number: 244,
    title: "docs: add comprehensive API reference for webhooks",
    description: "Adds complete API documentation for the webhook system including event types, payload schemas, and security verification.",
    authorId: "u4",
    author: "Taylor West",
    reviewers: ["u2"],
    status: "open",
    branch: "docs/webhook-api",
    baseBranch: "main",
    commitsCount: 2,
    changedFiles: 5,
    additions: 412,
    deletions: 12,
    createdAt: "2024-03-12T14:00:00Z",
    updatedAt: "2024-03-12T14:00:00Z",
    commentCount: 1,
    labels: ["documentation"],
  },
  {
    id: "pr-5",
    number: 243,
    title: "perf: optimize database query for PR listing with pagination",
    description: "Significant performance improvements to the PR listing endpoint. Query time reduced by 87% through proper indexing and cursor-based pagination.",
    authorId: "u1",
    author: "Alex Rivera",
    reviewers: ["u3"],
    status: "approved",
    branch: "perf/pr-listing-query",
    baseBranch: "main",
    commitsCount: 4,
    changedFiles: 3,
    additions: 55,
    deletions: 98,
    createdAt: "2024-03-11T08:00:00Z",
    updatedAt: "2024-03-11T15:20:00Z",
    commentCount: 5,
    labels: ["performance"],
  },
];

export const MOCK_COMMENTS = {
  "pr-1": [
    {
      id: "c1",
      userId: "u2",
      author: "Sam Chen",
      avatar: "SC",
      content: "This is a great approach! The CRDT implementation looks solid. One concern though — have you benchmarked the memory overhead with large documents?",
      timestamp: "2024-03-15T11:00:00Z",
      line: 42,
      file: "src/collab/crdt.ts",
      replies: [
        {
          id: "c1r1",
          userId: "u1",
          author: "Alex Rivera",
          avatar: "AR",
          content: "Good catch! I ran benchmarks with 10k-word docs and saw ~12MB overhead vs ~2MB previously. I'm adding lazy serialization in the next commit to bring it down.",
          timestamp: "2024-03-15T11:30:00Z",
        }
      ]
    },
    {
      id: "c2",
      userId: "u3",
      author: "Jordan Kim",
      avatar: "JK",
      content: "The operational transform fallback is a smart safety net. But shouldn't we have a feature flag to disable CRDT in case of issues in production?",
      timestamp: "2024-03-15T12:15:00Z",
      line: 87,
      file: "src/collab/sync.ts",
      replies: []
    },
    {
      id: "c3",
      userId: "u2",
      author: "Sam Chen",
      avatar: "SC",
      content: "Line 127: The mutex acquisition might cause a deadlock if the timeout callback fires before the lock is released. Can you add a guard here?",
      timestamp: "2024-03-15T13:00:00Z",
      line: 127,
      file: "src/collab/crdt.ts",
      replies: []
    },
  ],
};

export const MOCK_DIFF = [
  { type: "neutral", lineNo: { old: 1, new: 1 }, content: "  import { Document } from './types';" },
  { type: "neutral", lineNo: { old: 2, new: 2 }, content: "  import { EventEmitter } from 'events';" },
  { type: "add", lineNo: { old: null, new: 3 }, content: "+ import { CRDTDocument, Automerge } from '@syncedstore/core';" },
  { type: "add", lineNo: { old: null, new: 4 }, content: "+ import { OperationalTransform } from './ot-fallback';" },
  { type: "neutral", lineNo: { old: 3, new: 5 }, content: "  " },
  { type: "neutral", lineNo: { old: 4, new: 6 }, content: "  export class CollaborationManager extends EventEmitter {" },
  { type: "remove", lineNo: { old: 5, new: null }, content: "-   private locks: Map<string, Mutex> = new Map();" },
  { type: "remove", lineNo: { old: 6, new: null }, content: "-   private documents: Map<string, Document> = new Map();" },
  { type: "add", lineNo: { old: null, new: 7 }, content: "+   private crdtDocs: Map<string, CRDTDocument> = new Map();" },
  { type: "add", lineNo: { old: null, new: 8 }, content: "+   private otFallback: OperationalTransform;" },
  { type: "add", lineNo: { old: null, new: 9 }, content: "+   private useCRDT: boolean = process.env.FEATURE_CRDT === 'true';" },
  { type: "neutral", lineNo: { old: 7, new: 10 }, content: "  " },
  { type: "neutral", lineNo: { old: 8, new: 11 }, content: "    constructor() {" },
  { type: "neutral", lineNo: { old: 9, new: 12 }, content: "      super();" },
  { type: "add", lineNo: { old: null, new: 13 }, content: "+     this.otFallback = new OperationalTransform();" },
  { type: "remove", lineNo: { old: 10, new: null }, content: "-     this.initializeLocks();" },
  { type: "neutral", lineNo: { old: 11, new: 14 }, content: "    }" },
  { type: "neutral", lineNo: { old: 12, new: 15 }, content: "  " },
  { type: "remove", lineNo: { old: 13, new: null }, content: "-   async acquireLock(docId: string): Promise<void> {" },
  { type: "remove", lineNo: { old: 14, new: null }, content: "-     const mutex = this.locks.get(docId) || new Mutex();" },
  { type: "remove", lineNo: { old: 15, new: null }, content: "-     await mutex.acquire();" },
  { type: "remove", lineNo: { old: 16, new: null }, content: "-   }" },
  { type: "add", lineNo: { old: null, new: 16 }, content: "+   async applyChange(docId: string, change: Change): Promise<void> {" },
  { type: "add", lineNo: { old: null, new: 17 }, content: "+     if (this.useCRDT) {" },
  { type: "add", lineNo: { old: null, new: 18 }, content: "+       const doc = this.crdtDocs.get(docId) ?? Automerge.init();" },
  { type: "add", lineNo: { old: null, new: 19 }, content: "+       const [newDoc] = Automerge.applyChanges(doc, [change]);" },
  { type: "add", lineNo: { old: null, new: 20 }, content: "+       this.crdtDocs.set(docId, newDoc);" },
  { type: "add", lineNo: { old: null, new: 21 }, content: "+     } else {" },
  { type: "add", lineNo: { old: null, new: 22 }, content: "+       await this.otFallback.apply(docId, change);" },
  { type: "add", lineNo: { old: null, new: 23 }, content: "+     }" },
  { type: "add", lineNo: { old: null, new: 24 }, content: "+   }" },
];

export const MOCK_NOTIFICATIONS = [
  { id: "n1", type: "review", message: "Sam Chen approved PR #246", time: "2m ago", read: false, prId: "pr-2" },
  { id: "n2", type: "comment", message: "Jordan Kim commented on PR #247", time: "15m ago", read: false, prId: "pr-1" },
  { id: "n3", type: "pr", message: "New PR #247 opened by Alex Rivera", time: "1h ago", read: true, prId: "pr-1" },
  { id: "n4", type: "review", message: "Alex Rivera requested changes on PR #245", time: "3h ago", read: true, prId: "pr-3" },
  { id: "n5", type: "comment", message: "Sam Chen replied to your comment", time: "5h ago", read: true, prId: "pr-1" },
];

export const MOCK_ANALYTICS = {
  weeklyActivity: [
    { day: "Mon", opened: 4, merged: 2, rejected: 1 },
    { day: "Tue", opened: 6, merged: 5, rejected: 0 },
    { day: "Wed", opened: 3, merged: 4, rejected: 2 },
    { day: "Thu", opened: 8, merged: 3, rejected: 1 },
    { day: "Fri", opened: 5, merged: 6, rejected: 0 },
    { day: "Sat", opened: 1, merged: 2, rejected: 0 },
    { day: "Sun", opened: 2, merged: 1, rejected: 1 },
  ],
  reviewTime: [
    { label: "< 1h", value: 12 },
    { label: "1-4h", value: 28 },
    { label: "4-24h", value: 35 },
    { label: "1-3d", value: 18 },
    { label: "> 3d", value: 7 },
  ],
  approvalRate: [
    { name: "Approved", value: 68, color: "#3fb950" },
    { name: "Rejected", value: 12, color: "#f85149" },
    { name: "Pending", value: 20, color: "#7d8590" },
  ],
  topReviewers: [
    { name: "Sam Chen", reviews: 47, avatar: "SC" },
    { name: "Alex Rivera", reviews: 39, avatar: "AR" },
    { name: "Jordan Kim", reviews: 31, avatar: "JK" },
    { name: "Taylor West", reviews: 14, avatar: "TW" },
  ],
  metrics: {
    avgReviewTime: "4.2h",
    approvalRate: "68%",
    openPRs: 12,
    mergedThisWeek: 23,
  },
};
